149 how to add new modules
rpa-tomorrow/substorm-nlp pull request #201
Opened 2020-12-08 12:24 UTC by Blinningjr

# Proposed changes
* Added a automation module template
* Added development documentation on how to implement a automation module.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

- Read the documentation and the template to see if it makes sense.

# Related issue
Fixes #149 

# Checkboxes
- [ ] I have run the unit tests with `pytest`
- [ ] I formatted the changes with `./scripts/formatter.sh`

2020-12-08 12:54 UTC, Aleman778 requested changes
Looks good! Some small errors I found.

2020-12-08 12:54 UTC, Aleman778 commented on docs/automation_module.md
> +In `requirments.txt` a link to the releases NLP models must be added or updated.
Should be requirements.txt

2020-12-08 12:54 UTC, Aleman778 commented on docs/automation_module.md
> +* `to` is the list of contacts that user want to send a email to for example.
an email

2020-12-08 12:54 UTC, Aleman778 commented on docs/automation_module.md
> +The job of this method is to take the parsed input form the NLP model and process it so that the `execute` method can run. This can be thinks like finding en email related to a name or giving followu
Second sentence. Correction: This can be _things_ like ...

2020-12-08 14:01 UTC, Aleman778 approved these changes

2020-12-09 09:14 UTC, viktorfrom approved these changes

2020-12-09 09:18 UTC, merged